name: ExtraHeads
version: ${project.version}
author: TheBusyBiscuit
description: 此插件為繁體翻譯版, 原作者"TheBusyBiscuit".
depend: [Slimefun]

main: io.github.thebusybiscuit.extraheads.ExtraHeads
api-version: 1.13